api/urls.py
from django.urls import (path, include)
from rest_framework import routers

from .views import (IdemViewSet, UserViewSet)


router = routers.DefaultRouter()
router.register(r'idems', IdemViewSet)
router.register(r'users', UserViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('auth/', include('rest_framework.urls', namespace='rest_framework'))
]

comment/urls.py
from django.urls import path

from .views import (CommentView, CommentUpdateView, CommentDeleteView)


app_name = 'comment'

urlpatterns = [
    path('<int:pk>/edit/', CommentUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', CommentDeleteView.as_view(), name='delete'),
    path('<int:pk>/', CommentView.as_view(), name='view'),
]

idem/urls.py
from django.urls import (include, path)

from message.views import MessageCreateView

from .views import (IdemCreateView, IdemView, IdemSwitchView, IdemFollowView, IdemUnfollowView, IdemSettingsView,
                    IdemDeleteView, IdemIconsView)


app_name = 'idem'

urlpatterns = [
    path('create/', IdemCreateView.as_view(), name='create'),
    path('<slug:slug>/', IdemView.as_view(), name='idem'),
    path('<slug:slug>/switch/', IdemSwitchView.as_view(), name='switch'),
    path('<slug:idem>/follow/', IdemFollowView.as_view(), name='follow'),
    path('<slug:idem>/unfollow/', IdemUnfollowView.as_view(), name='unfollow'),
    path('<slug:idem>/blog/', include('blog.urls', namespace="blog")),
    path('<slug:idem>/collection/', include('collection.urls', namespace="collection")),
    path('<slug:idem>/comment/', include('comment.urls', namespace="comment")),
    path('<slug:idem>/gallery/', include('gallery.urls', namespace="gallery")),
    path('<slug:idem>/inbox/', include('message.urls', namespace="inbox")),
    path('<slug:idem>/message/', include('message.urls', namespace="message")),
    path('<slug:idem>/post/', include('post.urls', namespace="post")),
    path('<slug:idem>/story/', include('story.urls', namespace="story")),
    path('<slug:idem>/video/', include('video.urls', namespace="video")),
    path('<slug:idem>/search/', include('search.urls', namespace="search")),
    path('<slug:slug>/settings/', IdemSettingsView.as_view(), name='settings'),
    path('<slug:slug>/icons/', IdemIconsView.as_view(), name='icons'),
    path('<slug:slug>/delete/', IdemDeleteView.as_view(), name='delete'),
]

post/urls.py
from django.urls import path

from .views import (PermanentPostView, PostCreateView, PostTagView, PostLikeView)


app_name = 'post'

urlpatterns = [
    path('<str:hash>/', PermanentPostView.as_view(), name='permanent'),
    path('<str:hash>/like/', PostLikeView.as_view(), name='like'),
    path('tags/', PostTagView.as_view(), name='tags'),
    path('', PostCreateView.as_view(), name='create')
]

comment/models.py
from django.db import models

from post.models.related import RelatedManager
from core.helpers import teaser


class CommentManager(RelatedManager):
    def get_queryset(self):
        return super().get_queryset().select_related('parent').annotate(
            count_children=models.Count('children')
        )


class Comment(models.Model):
    post = models.ForeignKey('post.Post', related_name='comments', on_delete=models.CASCADE)
    parent = models.ForeignKey('comment.Comment', related_name='children', on_delete=models.PROTECT, blank=True, null=True)
    idem = models.ForeignKey('idem.Idem', related_name='+', on_delete=models.SET_NULL, null=True, blank=True)
    user = models.ForeignKey('account.User', related_name='+', on_delete=models.SET_NULL, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    edited = models.DateTimeField(auto_now=True)
    text = models.TextField()
    is_deleted = models.BooleanField(default=False)
    is_flagged = models.BooleanField(default=False)

    objects = CommentManager()

    def by(self):
        if self.idem:
            return self.idem

        elif self.user:
            return self.user

        return 'Anon'

    def __str__(self):
        return teaser(self.text, 200)

comment/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    parent = forms.IntegerField(widget=forms.HiddenInput, required=False)

    def clean_parent(self):
        if not isinstance(self.cleaned_data.get('parent'), int):
            return None

        try:
            comment = Comment.objects.get(pk=self.cleaned_data.get('parent'))
            return comment

        except Comment.DoesNotExist:
            return None

    class Meta:
        model = Comment
        fields = ['text', 'parent']

    def __init__(self, *args, **kwargs):
        if 'idem' in kwargs:
            self.idem = kwargs.pop('idem')

        super().__init__(*args, **kwargs)


class CommentDeleteForm(forms.ModelForm):
    is_deleted = forms.BooleanField(widget=forms.HiddenInput, required=False)

    def clean_is_deleted(self):
        return True

    class Meta:
        model = Comment
        fields = ['is_deleted', ]

    def __init__(self, *args, **kwargs):
        if 'idem' in kwargs:
            self.idem = kwargs.pop('idem')

        super().__init__(*args, **kwargs)

comment/views.py
from django.contrib import messages
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.views.generic import (DetailView, UpdateView)

from idem.view_mixins import IdemMixin

from .decorators import comment_or_post_owner_required
from .forms import (CommentForm, CommentDeleteForm)
from .models import Comment


class CommentView(IdemMixin, DetailView):
    template_name = 'comment/view.html'
    model = Comment


@method_decorator(comment_or_post_owner_required, name='dispatch')
class CommentUpdateView(IdemMixin, UpdateView):
    template_name = 'comment/update.html'
    model = Comment
    form_class = CommentForm

    def get_success_url(self):
        messages.success(self.request, 'Your comment has been edited')
        return self.object.post.specific.full_url


@method_decorator(comment_or_post_owner_required, name='dispatch')
class CommentDeleteView(IdemMixin, UpdateView):
    template_name = 'comment/delete.html'
    model = Comment
    form_class = CommentDeleteForm

    def form_valid(self, form):
        messages.success(self.request, 'Poof! Comment gone!')

        if form.instance.count_children:
            form.instance.is_deleted = True
            return super().form_valid(form)

        form.instance.delete()
        return redirect(self.get_success_url())

    def get_success_url(self):
        return self.object.post.specific.full_url

comment/templates/comment/_comment.html
{% load humanize %}

{% if not comment.is_deleted %}
    <h6 class="d-flex">
        <span class="w-100">
            {% if comment.idem.id %}
                <a href="{{ comment.idem.full_url }}">{{ comment.by }}</a>
            {% else %}
                {{ comment.by }}
            {% endif %}
            <span title="{{ comment.created }}">{{ comment.created|naturaltime }}</span>
            {% if comment.edited %}
                 (edited {{ comment.edited|naturaltime }})
            {% endif %}
        </span>
        <span class="flex-shrink-1 text-nowrap">
            {% if comment.parent and comment.count_children %}
                <a href="#" class="comment-expand" data-parent="{{ comment.id }}"><i class="fa fa-comments-o"></i> Thread</a>
            {% endif %}
            {% if allow_comments %}
                <a href="#" class="comment-reply" data-parent="{{ comment.id }}"><i class="fa fa-comment-o"></i> Reply</a>
            {% endif %}
            {% if comment.user.id == user.id %}
                <a href="{% url 'idem:comment:update' idem.slug comment.id %}"><i class="fa fa-pencil"></i> Edit</a>
            {% endif %}
            {% if comment.user.id == user.id or comment.post.idem.id == user.idem.id %}
                <a href="{% url 'idem:comment:delete' idem.slug comment.id %}"><i class="fa fa-trash"></i> Delete</a>
            {% endif %}
        </span>
    </h6>
    <p>{{ comment.text|linebreaksbr }}</p>
{% else %}
    <p>Deleted</p>
{% endif %}

comment/templates/comment/_comments.html
{% load bootstrap4 comment_tags %}

<style>
    #commentForm textarea {height: 100px}
</style>

{% block javascript_body %}
    {{ super.block }}
    {% if allow_comments %}
    <script>
        $( document ).ready(function() {
            var commentParent = $('#id_parent');

            var commentForm = $('#commentForm');
                commentForm.detach();

            $('.comment-reply').click(function(e){
                e.preventDefault();

                $(this).parent().parent().parent().append(commentForm);

                if ($(this).attr('data-parent')) {
                    commentParent.val($(this).attr('data-parent'));
                } else {
                    commentParent.val();
                }
            });

            {% if open_parent %}
                $('a.comment-reply[data-parent="{{ open_parent }}"]').click();
            {% endif %}
        });
    </script>
    {% endif %}
{% endblock %}

{% if allow_comments %}
<div class="comment comment-parent">
    <div class="d-flex">
        <span class="w-100"></span>
        <span class="flex-shrink-1 text-nowrap">
            <a href="#" class="comment-reply" data-parent="0"><i class="fa fa-comments-o"></i> Reply</a>
        </span>
    </div>
    <form method="post" action="{{ request.path }}" id="commentForm">
        {% csrf_token %}
        {% bootstrap_form form layout="inline" %}
        <button type="submit" class="btn btn-primary"><i class="fa fa-comment"></i> Comment</button>
    </form>
</div>
{% endif %}

<p>{{ comment.text|linebreaksbr }}</p>

{% if comments %}
<div id="commentThreads">
    {% for comment in comments %}
        <div class="comment comment-parent">
            {% post_comment comment idem=idem allow_comments=allow_comments %}
        </div>
        <div class="comment-children pl-3">
        {% for thread in comment.threads %}
            <div class="comment comment-thread">{% post_comment thread idem=idem allow_comments=allow_comments %}</div>
        {% endfor %}
        </div>
    {% endfor %}
</div>
{% endif %}

comment/templates/comment/delete.html
{% extends 'idem/idem.html' %}

{% block main %}
    <form method="post" action="{% url 'idem:comment:delete' idem.slug comment.id %}">
        {% csrf_token %}
        {{ form }}
        <p>Sure?</p>
        <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Sure!</button>
    </form>
{% endblock %}

comment/templates/comment/update.html
{% extends 'idem/idem.html' %}
{% load bootstrap4 %}
{% block main %}
    <form method="post" action="{% url 'idem:comment:update' idem.slug comment.id %}">
        {% csrf_token %}
        {% bootstrap_form form layout="inline" %}
        <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Update</button>
    </form>
{% endblock %}