alteridem/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import (include, path)
from django.views.generic import RedirectView


urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url=settings.STATIC_URL + 'main/img/favicon.ico')),
    path('hijack/', include('hijack.urls', namespace='hijack')),
    # path('api/v1/', include('api.urls')),
    path('blog/', include('blog.urls', namespace="blog")),
    path('collection/', include('collection.urls', namespace="collection")),
    path('comment/', include('comment.urls', namespace="comment")),
    path('gallery/', include('gallery.urls', namespace="gallery")),
    path('post/', include('post.urls', namespace="post")),
    path('story/', include('story.urls', namespace="story")),
    path('video/', include('video.urls', namespace="video")),
    path('search/', include('search.urls', namespace="results")),
    path('inbox/', include('message.urls', namespace="message")),
    path('', include('account.urls', namespace="account")),
    path('', include('main.urls', namespace="main")),
    path('', include('idem.urls', namespace="idem")),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] \
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
        + urlpatterns

api/urls.py
from django.urls import (path, include)
from rest_framework import routers

from .views import (IdemViewSet, UserViewSet)


router = routers.DefaultRouter()
router.register(r'idems', IdemViewSet)
router.register(r'users', UserViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('auth/', include('rest_framework.urls', namespace='rest_framework'))
]

idem/urls.py
from django.urls import (include, path)

from message.views import MessageCreateView

from .views import (IdemCreateView, IdemView, IdemSwitchView, IdemFollowView, IdemUnfollowView, IdemSettingsView,
                    IdemDeleteView, IdemIconsView)


app_name = 'idem'

urlpatterns = [
    path('create/', IdemCreateView.as_view(), name='create'),
    path('<slug:slug>/', IdemView.as_view(), name='idem'),
    path('<slug:slug>/switch/', IdemSwitchView.as_view(), name='switch'),
    path('<slug:idem>/follow/', IdemFollowView.as_view(), name='follow'),
    path('<slug:idem>/unfollow/', IdemUnfollowView.as_view(), name='unfollow'),
    path('<slug:idem>/blog/', include('blog.urls', namespace="blog")),
    path('<slug:idem>/collection/', include('collection.urls', namespace="collection")),
    path('<slug:idem>/comment/', include('comment.urls', namespace="comment")),
    path('<slug:idem>/gallery/', include('gallery.urls', namespace="gallery")),
    path('<slug:idem>/inbox/', include('message.urls', namespace="inbox")),
    path('<slug:idem>/message/', include('message.urls', namespace="message")),
    path('<slug:idem>/post/', include('post.urls', namespace="post")),
    path('<slug:idem>/story/', include('story.urls', namespace="story")),
    path('<slug:idem>/video/', include('video.urls', namespace="video")),
    path('<slug:idem>/search/', include('search.urls', namespace="search")),
    path('<slug:slug>/settings/', IdemSettingsView.as_view(), name='settings'),
    path('<slug:slug>/icons/', IdemIconsView.as_view(), name='icons'),
    path('<slug:slug>/delete/', IdemDeleteView.as_view(), name='delete'),
]

post/urls.py
from django.urls import path

from .views import (PermanentPostView, PostCreateView, PostTagView, PostLikeView)


app_name = 'post'

urlpatterns = [
    path('<str:hash>/', PermanentPostView.as_view(), name='permanent'),
    path('<str:hash>/like/', PostLikeView.as_view(), name='like'),
    path('tags/', PostTagView.as_view(), name='tags'),
    path('', PostCreateView.as_view(), name='create')
]

post/models/post.py
import ast

from copy import deepcopy

from django.conf import settings
from django.db import models
from django.db.models.functions import Coalesce
from django.shortcuts import reverse
from django.utils import timezone
from django.utils.html import (strip_tags, mark_safe)

from autoslugged import AutoSlugField
from django_cryptography.fields import encrypt
from taggit.managers import TaggableManager

from core.helpers import (EnumChoices, teaser)
from tags.models import IdemTaggedItem

from search.elasticsearch import PostIndex

from .related import Like
from ..settings import POST_HASH


class PostManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset() \
            .select_related('idem') \
            .select_related('parent') \
            .select_related('credit') \
            .annotate(
                count_annotations=models.Count('annotations'),
                count_bookmarks=models.Count('bookmarks'),
                count_children=models.Count('children'),
                count_comments=models.Count('comments'),
                count_credits=models.Count('credits'),
                count_likes=models.Count('likes'),
                total_annotations=Coalesce(models.Sum('children__annotations'), 0),
                total_bookmarks=Coalesce(models.Sum('children__bookmarks'), 0),
                total_comments=Coalesce(models.Sum('children__comments'), 0),
                total_likes=Coalesce(models.Sum('children__likes'), 0),
                total_words=Coalesce(models.Sum('children__words'), 0),
            ).order_by('-children__publish', '-publish', '-id')

    def dashboard(self, idem):
        # what appears on a given idem's dashboard of people they're watching

        return self.get_queryset() \
            .exclude(access=0) \
            .filter(parent__isnull=True) \
            .filter(publish__lte=timezone.now()) \
            .filter(idem_id__in=idem.following.values_list('followers__to_idem_id', flat=True)) \
            .filter(idem__is_active=True)\
            .annotate(liked=models.Subquery(Like.objects.filter(post=models.OuterRef('pk'), idem=idem).values('pk')))

    def owner(self, idem, user=None):
        # what appears on an idem's landing page for owner

        qs = self.get_queryset().filter(idem=idem).exclude(parent__isnull=False)

        return self._annotate_liked(qs, user)

    def visitor(self, idem, user=None):
        # what appears on an idem's landing page for visitor

        qs = self.get_queryset()\
            .filter(idem=idem)\
            .exclude(parent__isnull=False)\
            .exclude(publish=None)\
            .exclude(access=0)\
            .filter(publish__lte=timezone.now())

        return self._annotate_liked(qs, user)

    @staticmethod
    def _annotate_liked(qs, user):
        try:
            liked = Like.objects.filter(post=models.OuterRef('pk'), idem_id=user.idem.id)
            qs = qs.annotate(liked=models.Subquery(liked.values('pk')))
        except AttributeError:
            pass

        return qs


class Post(models.Model):
    class RATINGS(EnumChoices):
        not_rated = (0, 'Not rated')
        everyone = (1, 'Everyone')
        ya = (2, 'Young adult (13+)')
        adult = (3, 'Adult (18+)')
        explicit = (4, 'Explicit')

    class WARNINGS(EnumChoices):
        surprise = (1, 'Enter at your own risk')
        triggers = (2, 'May be triggering')
        other = (3, 'Custom warning')

    class ACCESS(EnumChoices):
        private = (0, 'Private')
        password = (1, 'Password protected')
        filtered = (2, 'Filtered')
        followers = (3, 'Followers')
        public = (4, 'Public')

    idem = models.ForeignKey('idem.Idem', related_name='posts', on_delete=models.CASCADE)
    icon = models.ForeignKey('idem.Icon', related_name='+', on_delete=models.SET_NULL, blank=True, null=True)
    parent = models.ForeignKey('post.Post', related_name='children', on_delete=models.SET_NULL, null=True, blank=True)
    credit = models.ForeignKey('post.Post', related_name='credits', on_delete=models.SET_NULL, null=True, blank=True)
    mode = models.CharField(max_length=10, db_index=True)
    created = models.DateTimeField(auto_now_add=True)
    publish = models.DateTimeField(blank=True, null=True)
    rating = models.IntegerField(default=0, choices=[x.value for x in RATINGS], db_index=True)
    warnings = models.CharField(blank=True, max_length=255)
    warnings_custom = models.CharField(blank=True, max_length=255)
    age = models.IntegerField(blank=True, default=0)
    password = encrypt(models.CharField(max_length=255, blank=True))
    title = models.CharField(max_length=255, blank=True)
    slug = AutoSlugField(populate_from='title', unique_with=['publish', 'idem'], always_update=True)
    description = models.TextField(blank=True)
    text = models.TextField(blank=True)
    order = models.IntegerField(default=0)
    words = models.IntegerField(default=0)
    link = models.URLField(blank=True, null=True)
    access = models.IntegerField(default=0, choices=[x.value for x in ACCESS], db_index=True)

    allow_likes = models.BooleanField(default=True)
    allow_share = models.BooleanField(default=True)
    allow_annotate = models.BooleanField(default=True)
    allow_comments = models.NullBooleanField(default=True)  # no / members / anyone
    allow_credit = models.BooleanField(default=True)  # allow post based on this post

    allow_search = models.BooleanField(default=True)
    allow_indexing = models.BooleanField(default=False)

    x_post_dw = models.BooleanField(default=False)
    x_post_lj = models.BooleanField(default=False)
    x_post_tumblr = models.BooleanField(default=False)

    tags = TaggableManager(through=IdemTaggedItem, blank=True)

    objects = PostManager()

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.mode:
            self.mode = self.__class__.__name__.lower()

        self.words = len(strip_tags(self.text).replace("\n", " ").split(" "))

        super().save(force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)

    @property
    def specific(self):
        if isinstance(self, Post):
            for _class in Post.__subclasses__():
                if self.mode == _class.__name__.lower():
                    copy = deepcopy(self)
                    copy.__class__ = _class
                    return copy

        return self

    @property
    def teaser(self):
        return teaser(self.description or self.text)

    @property
    def hash(self):
        return POST_HASH.encode(self.id)

    @property
    def permanent_url(self):
        return reverse('post:permanent', kwargs={'hash': self.hash})

    @property
    def url(self):
        return self.permanent_url

    @property
    def full_url(self):
        return '{}{}'.format(settings.BASE_URL, self.url)

    @property
    def access_label(self):
        icons = ['lock', 'key', 'filter', 'users', 'unlock']

        return mark_safe("<i class='fa fa-{icon}' title='{label}'></i> {label}".format(
            icon=icons[self.access],
            label=self.ACCESS.label(self.access)
        ))

    def indexing(self):
        obj = PostIndex(meta={'index': 'post-index', 'id': self.id},
                        id=self.id,
                        idem=self.idem.title, publish=self.publish, title=self.title, text=self.text, mode=self.mode)
        obj.save()

        return obj.to_dict(include_meta=True)

    def __str__(self):
        return self.title

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.warnings:
            self.warnings = ast.literal_eval(self.warnings)

post/models/related.py
from django.core.exceptions import ValidationError
from django.db import models

from taggit.managers import TaggableManager

from tags.models import IdemTaggedItem


class RelatedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().select_related('post').select_related('idem')


class Annotation(models.Model):
    post = models.ForeignKey('post.Post', related_name='annotations', on_delete=models.CASCADE)
    idem = models.ForeignKey('idem.Idem', related_name='+', on_delete=models.SET_NULL, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    text = models.TextField(blank=True)
    quote = models.TextField()

    objects = RelatedManager()


class Bookmark(models.Model):
    post = models.ForeignKey('post.Post', related_name='bookmarks', on_delete=models.CASCADE)
    idem = models.ForeignKey('idem.Idem', related_name='bookmarks', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    public = models.BooleanField(default=True)
    rec = models.BooleanField(default=False)
    text = models.TextField(blank=True)
    tags = TaggableManager(through=IdemTaggedItem, blank=True)

    objects = RelatedManager()

    class Meta:
        unique_together = ('post', 'idem')


class Like(models.Model):
    post = models.ForeignKey('post.Post', related_name='likes', on_delete=models.CASCADE)
    idem = models.ForeignKey('idem.Idem', related_name='likes', on_delete=models.SET_NULL, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = RelatedManager()

    def validate_unique(self, exclude=None):
        if not self.idem:
            return super().validate_unique(exclude=exclude)

        if Like.objects.filter(post=self.post, idem=self.idem).exists():
            raise ValidationError("You've already liked {}!".format(self.post.title))

tags/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from taggit.models import (TagBase, GenericTaggedItemBase)

from core.helpers import EnumChoices


class IdemTag(TagBase):
    class MODE(EnumChoices):
        general = (0, 'General')
        character = (1, 'Character')
        relationship = (2, 'Relationship')
        category = (3, 'Category')
        fandom = (4, 'Fandom')

    mode = models.IntegerField(default=0, db_index=True)

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")


class IdemTaggedItem(GenericTaggedItemBase):
    tag = models.ForeignKey(IdemTag, related_name="%(app_label)s_%(class)s_items", on_delete=models.CASCADE)

post/views.py
from django.http import Http404
from django.shortcuts import (reverse, redirect)
from django.views.generic import (DetailView, ListView, TemplateView, RedirectView)

from taggit.models import Tag

from core.view_mixins import JSONResponseMixin
from idem.view_mixins import IdemMixin

from .models import (Post, Like)
from .settings import POST_HASH


class PermanentPostView(RedirectView):
    model = Post
    template_name = 'post/permanent.html'

    def get_redirect_url(self, *args, **kwargs):
        try:
            post = Post.objects.get(pk=POST_HASH.decode(self.kwargs.get('hash'))[0])

            if post.access or (self.request.user.is_authenticated
                               and self.request.user.id == post.idem.user.id):
                return post.specific.full_url

        except (Post.DoesNotExist, IndexError):
            pass

        raise Http404("Sorry, this post doesn't seem to be a thing")


class PostCreateView(IdemMixin, TemplateView):
    template_name = 'post/create.html'

    def dispatch(self, request, *args, **kwargs):
        if not self.idem and request.user.idem:
            return redirect(reverse('idem:post:create', kwargs={'idem': request.user.idem.slug}))

        return super().dispatch(request, *args, **kwargs)


class PostListView(IdemMixin, ListView):
    model = Post
    template_name = 'post/list.html'

    def get_queryset(self):
        if self.idem:
            if self.request.user.is_authenticated and self.idem.user_id == self.request.user.id:
                return self.model.objects.owner(self.idem, user=self.request.user)
            else:
                return self.model.objects.visitor(self.idem, user=self.request.user)
        else:
            # ToDo - probably remove this
            return self.model.objects.get_queryset()


class PostTagView(IdemMixin, JSONResponseMixin, TemplateView):
    template_name = 'post/tags.html'

    def format_json(self):
        return [tag.name for tag in Tag.objects.all()]

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        # ToDo filter with idem properly once know how...
        data.update({'tags': Tag.objects.all()})
        return data


class PostLikeView(JSONResponseMixin, DetailView):
    def get_object(self, queryset=None):
        try:
            post = Post.objects.get(pk=POST_HASH.decode(self.kwargs.get('hash'))[0])

            if post.allow_likes and (post.access or (self.request.user.is_authenticated
                                                     and self.request.user.id == post.idem.user.id)):
                return post

        except (Post.DoesNotExist, IndexError):
            pass

        raise Http404("Sorry, this post doesn't seem to be a thing")

    def get(self, request, *args, **kwargs):
        if request.user.idem:
            try:
                Like.objects.get(idem=request.user.idem, post=self.get_object()).delete()
            except Like.DoesNotExist:
                Like.objects.create(idem=request.user.idem, post=self.get_object())

        else:
            Like.objects.create(post=self.object)

        if request.is_ajax():
            return super().get(request, *args, **kwargs)

        return redirect(self.get_object().specific.full_url)

    def format_json(self):
        return {'success': True}

tags/views.py
from django.shortcuts import render

# Create your views here.

post/templates/post/_editor_options.html
<div id="editor_options">
    <div class="d-flex align-items-stretch btn-group">
        <button class="btn btn-sm btn-secondary" type="button" data-command="bold" data-type="format"><strong>B</strong></button>
        <button class="btn btn-sm btn-secondary" type="button" data-command="italic" data-type="format"><em>I</em></button>
        <button class="btn btn-sm btn-secondary" type="button" data-command="underline" data-type="format"><u>U</u></button>
        <button class="btn btn-sm btn-secondary" type="button" data-command="strikeThrough" data-type="format"><strike>S</strike></button>
        <button class="btn btn-sm btn-secondary" type="button" data-command="heading">H</button>
        <button class="btn btn-sm btn-secondary" type="button" data-command="createLink"><i class="fa fa-link"></i></button>
        <button class="btn btn-sm btn-secondary" type="button" data-command="unlink" data-type="format"><i class="fa fa-unlink"></i></button>
        <button class="btn btn-sm btn-secondary" type="button" data-command="insertOrderedList" data-type="format"><i class="fa fa-list-ol"></i></button>
        <button class="btn btn-sm btn-secondary" type="button" data-command="insertUnorderedList" data-type="format"><i class="fa fa-list-ul"></i></button>
        <button class="btn btn-sm btn-secondary" type="button" data-command="formatBlock"><i class="fa fa-quote-left"></i></button>
    </div>
</div>

post/templates/post/_libs.html
{% load static_version %}

<script src="{% static_version 'core/js/rich_text.js' %}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
<script type="text/javascript">
    $(function () {
        $('#datetimepicker').datetimepicker();
        $('#datetimepicker').on('change.datetimepicker', function(data) {
            if (data.date) {
                $('a[href="#collapseDate"] .text-nowrap').text(data.date.format('D MMM YYYY HH:mm'));
            }
        });
    });
</script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css">

post/templates/post/_list_breakdown.html
<li class="list-group-item px-0 d-flex justify-content-between align-items-center">
    <a href="{% url link idem.slug %}"><i class="fa fa-{{ icon }} fa-fw"></i> {{ name }}</a>
    <span class="badge badge-primary badge-pill">{{ count }}</span>
</li>

post/templates/post/_listing.html
{% load post_tags %}

{% for post in posts %}
    {% post_listing post show_all=True %}
    <div class="options">
        {% if post.allow_likes %}
            <a href="{% url 'post:like' post.hash %}" class="post-like">
                {% if post.liked %}
                    <i class="fa fa-heart text-danger"></i>
                {% else %}
                    <i class="fa fa-heart-o text-danger"></i>
                {% endif %}
            </a>
        {% endif %}
        {% if post.count_comments %}
            <a href="{{ post.specific.url }}#commentThreads"><i class="fa fa-comment-o"></i></a>
        {% endif %}

        <div class="btn-group dropup">
            <a href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-share-square-o"></i>
            </a>
            <div class="dropdown-menu post-share">
                <div class="post-share-embed">
                    <code>
                        &lt;div class="idem-embed" data-url="//alter-idem.com/embed/{{ post.hash }}"&gt;
                            &lt;a href="{{ post.specific.full_url }}"&gt;{{ post.specific.full_url }}&lt;/a&gt;
                        &lt;/div&gt;
                        &lt;script async src="//alter-idem.com/embed.js"&gt;&lt;/script&gt;
                    </code>
                </div>
                <div class="d-flex text-center">
                    <a href="{{ post.permanent_url }}" class="m-3"><i class="fa fa-link"></i><br>Permalink</a>
                    <a class="m-3"><i class="fa fa-code"></i><br>Embed</a>
                    <a class="m-3"><i class="fa fa-envelope-o"></i><br>E-mail</a>
                    <a class="m-3"><i class="fa fa-flag-o"></i><br>Report</a>
                    {% if post.allow_share %}
                        <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u={{ context.BASE_URL }}{{ post.permanent_url }}" class="m-3 post-share-window"><i class="fa fa-facebook"></i><br>Facebook</a>
                        <a target="_blank" href="https://twitter.com/intent/tweet?url={{ context.BASE_URL }}{{ post.permanent_url }}" class="m-3 post-share-window"><i class="fa fa-twitter"></i><br>Twitter</a>
                        <a target="_blank" href="https://www.tumblr.com/widgets/share/tool?shareSource=legacy&canonicalUrl={{ context.BASE_URL }}{{ post.permanent_url }}&url={{ post.specific.full_url }}&title={{ post.title }}&caption={{ post.description }}" class="m-3 post-share-window"><i class="fa fa-tumblr"></i><br>Tumblr</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% if context.request.user.idem %}
        <a href="{{ post.specific.url }}#commentThreads" title="Block idem"><i class="fa fa-ban"></i></a>
        {% endif %}
    </div>

{% endfor %}

post/templates/post/_tags.html
{% for tag in tags %}
    {% if idem %}
        <a href="{{ idem.full_url }}/{{ tag.slug }}">#{{ tag.name }}</a>
    {% else %}
        <a href="/{{ tag.slug }}">#{{ tag.name }}</a>
    {% endif %}
{% endfor %}

post/templates/post/form.html
{% extends 'idem/base.html' %}
{% load static bootstrap4 post_tags core_tags %}

{% block javascript_body %}
    {{ block.super }}
    {% post_libs %}
    {% if idem.icon %}
    <script>
        $('#id_icon').hide();
        $('#dropdownIconList img').click(function(e){
            $('#icon-preview').attr('src', $(this).attr('src'));
            $('#id_icon').val($(this).attr('data-id')*1);
        });
    </script>
    {% endif %}
{% endblock %}


{% block content %}
    {% include 'post/_editor_options.html' %}
    {% block post_form_tag %}
    <form method="post">
    {% endblock %}
        {% csrf_token %}
        {% bootstrap_form_errors form %}
        <div class="row">
            <div class="col-md-8">
                {% block post_form %}{% endblock %}
            </div>
            <div class="col-md-4">
                {% block post_options %}
                {% if idem.icon %}
                    <div class="dropdown">
                        <a href="#" role="button" class="btn dropdown-toggle" id="dropdownIconButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {% block post_icon %}<img src="{{ idem.icon.image.url }}" id="icon-preview">{% endblock %}
                        </a>
                        <div class="dropdown-menu pt-4 px-4" aria-labelledby="dropdownIconButton">
                            <div class="row" id="dropdownIconList">
                                {% for icon in idem.icons.all %}
                                    <div class="col-md-4"><img src="{{ icon.image.url }}" data-id="{{ icon.id }}" class="img-fluid mb-4"></div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    {% bootstrap_field form.icon layout="inline" %}
                {% endif %}
                <a data-toggle="collapse" class="post-option d-flex" href="#collapseDate" role="button" aria-expanded="false" aria-controls="collapseDate">
                    <span class="w-100"><i class="fa fa-square-o"></i> Publish</span>
                    <span class="flex-shrink-1 text-nowrap">{% block post_publish %}{% endblock %}</span>
                </a>
                <div class="collapse" id="collapseDate">
                    <div class="form-group">
                        <div class="input-group date" id="datetimepicker" data-target-input="nearest">
                            <label class="sr-only" for="id_publish">Publish</label>
                            <input id="id_publish" type="text" name="publish" class="form-control datetimepicker-input" value="{% block post_publish_value %}{% endblock %}" data-target="#datetimepicker">
                            <div class="input-group-append" data-target="#datetimepicker" data-toggle="datetimepicker">
                                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                            </div>
                        </div>
                    </div>
                </div>
                <a data-toggle="collapse" class="post-option d-flex" href="#collapseAccess" role="button" aria-expanded="false" aria-controls="collapseAccess">
                    <span class="w-100"><i class="fa fa-square-o"></i> Access</span>
                    <span class="flex-shrink-1 text-nowrap"></span>
                </a>
                <div class="collapse" id="collapseAccess">
                    {% bootstrap_field form.access layout="inline" %}
                    {% password_show_hide form.password %}
                    <hr>
                    {% bootstrap_field form.rating layout="inline" %}
                    {% bootstrap_field form.age layout="horizontal" %}
                    <hr>
                    {% bootstrap_field form.warnings layout="inline" %}
                    {% bootstrap_field form.warnings_custom layout="inline" %}
                    <hr>
                    <div class="row">
                        <div class="col">{% bootstrap_field form.allow_search layout="inline" %}</div>
                        <div class="col">{% bootstrap_field form.allow_indexing layout="inline" %}</div>
                    </div>
                </div>

                {% if idem.can_x_post %}
                    <a data-toggle="collapse" class="post-option d-flex" href="#collapseCrossPost" role="button" aria-expanded="false" aria-controls="collapseCrossPost">
                        <span class="w-100"><i class="fa fa-square-o"></i> Cross-post</span>
                        <span class="flex-shrink-1 text-nowrap">
                            {% if idem.can_x_post_dw %}
                                <i class="fa fa-times" data-site="dw" title="No"></i> dreamwidth
                            {% endif %}
                            {% if idem.can_x_post_lj %}
                                <i class="fa fa-times" data-site="lj" title="No"></i> livejournal
                            {% endif %}
                            {% if idem.can_x_post_tumblr %}
                                <i class="fa fa-times" data-site="tumblr" title="No"></i> tumblr
                            {% endif %}
                        </span>
                    </a>
                    <div class="collapse" id="collapseCrossPost">
                        {% if idem.can_x_post_dw %}{% bootstrap_field form.x_post_dw layout="inline" %}{% endif %}
                        {% if idem.can_x_post_lj %}{% bootstrap_field form.x_post_lj layout="inline" %}{% endif %}
                        {% if idem.can_x_post_tumblr %}{% bootstrap_field form.x_post_tumblr layout="inline" %}{% endif %}
                    </div>
                {% endif %}

                <a data-toggle="collapse" class="post-option d-flex" href="#collapseSharing" role="button" aria-expanded="false" aria-controls="collapseSharing">
                    <span class="w-100"><i class="fa fa-square-o"></i> Responses</span>
                    <span class="flex-shrink-1 text-nowrap">
                        <i class="fa fa-times" title="No"></i> likes
                        <i class="fa fa-times" title="No"></i> sharing
                        <i class="fa fa-times" title="No"></i> comments
                    </span>
                </a>
                <div class="collapse" id="collapseSharing">
                    <div class="row">
                        <div class="col-5">{% bootstrap_field form.allow_likes layout="inline" %}</div>
                        <div class="col-7">{% bootstrap_field form.allow_share layout="inline" %}</div>
                    </div>
                    <h6>Allow comments</h6>
                    <div class="form-group">
                        <div class="form-check form-check-inline">
                          {{ form.allow_comments.0 }}
                        </div>
                        <div class="form-check form-check-inline">
                          {{ form.allow_comments.1 }}
                        </div>
                        <div class="form-check form-check-inline">
                          {{ form.allow_comments.2 }}
                        </div>
                    </div>
                </div>

                <a data-toggle="collapse" class="post-option d-flex" href="#collapseRelated" role="button" aria-expanded="false" aria-controls="collapseRelated">
                    <span class="w-100"><i class="fa fa-square-o"></i> Related</span>
                    <span class="flex-shrink-1 text-nowrap">
                        <i class="fa fa-times" title="No"></i> link backs
                        <i class="fa fa-times" title="No"></i> related post
                    </span>
                </a>
                <div class="collapse" id="collapseRelated">
                    {% bootstrap_field form.credit %}
                    {% bootstrap_field form.allow_credit layout="inline" %}
                </div>
                {% endblock %}
            </div>
        </div>
    </form>
{% endblock %}

post/templates/post/permanent.html
{% extends 'main/base.html' %}
{% block content %}
    <h1>{{ post.title }}</h1>
    {{ post.text|safe }}
    {% for tag in post.tags.all %}
    {{ tag }}
    {% endfor %}
{% endblock %}