account/urls.py
from django.urls import path

from .views import (LoginView, LogoutView, RegisterView, ValidateView, ProfileView, ResendValidationView,
                    PasswordResetView, PasswordResetConfirmView, CookiesView, PasswordChangeView, AccountDeleteView)


app_name = 'account'

urlpatterns = [
    path('create-account/', RegisterView.as_view(), name='register'),
    path('validate/<slug:uidb64>/<slug:token>/', ValidateView.as_view(), name='validate'),
    path('validate/', ResendValidationView.as_view(), name='resend_validate'),
    path('login/', LoginView.as_view(), name='login'),
    path('login/password', PasswordResetView.as_view(), name='password_reset'),
    path('login/password/<slug:uidb64>/<slug:token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/password', PasswordChangeView.as_view(), name='password'),
    path('profile/delete', AccountDeleteView.as_view(), name='delete'),
    path('cookies/', CookiesView.as_view(), name='cookies'),
]

api/urls.py
from django.urls import (path, include)
from rest_framework import routers

from .views import (IdemViewSet, UserViewSet)


router = routers.DefaultRouter()
router.register(r'idems', IdemViewSet)
router.register(r'users', UserViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('auth/', include('rest_framework.urls', namespace='rest_framework'))
]

blog/urls.py
from django.urls import path

from .views import (BlogCreateView, BlogUpdateView, BlogDeleteView, BlogView, BlogListView)


app_name = 'blog'

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/edit', BlogUpdateView.as_view(), name='update'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/delete', BlogDeleteView.as_view(), name='delete'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', BlogView.as_view(), name='entry'),
    path('', BlogListView.as_view(), name='list'),
]

idem/urls.py
from django.urls import (include, path)

from message.views import MessageCreateView

from .views import (IdemCreateView, IdemView, IdemSwitchView, IdemFollowView, IdemUnfollowView, IdemSettingsView,
                    IdemDeleteView, IdemIconsView)


app_name = 'idem'

urlpatterns = [
    path('create/', IdemCreateView.as_view(), name='create'),
    path('<slug:slug>/', IdemView.as_view(), name='idem'),
    path('<slug:slug>/switch/', IdemSwitchView.as_view(), name='switch'),
    path('<slug:idem>/follow/', IdemFollowView.as_view(), name='follow'),
    path('<slug:idem>/unfollow/', IdemUnfollowView.as_view(), name='unfollow'),
    path('<slug:idem>/blog/', include('blog.urls', namespace="blog")),
    path('<slug:idem>/collection/', include('collection.urls', namespace="collection")),
    path('<slug:idem>/comment/', include('comment.urls', namespace="comment")),
    path('<slug:idem>/gallery/', include('gallery.urls', namespace="gallery")),
    path('<slug:idem>/inbox/', include('message.urls', namespace="inbox")),
    path('<slug:idem>/message/', include('message.urls', namespace="message")),
    path('<slug:idem>/post/', include('post.urls', namespace="post")),
    path('<slug:idem>/story/', include('story.urls', namespace="story")),
    path('<slug:idem>/video/', include('video.urls', namespace="video")),
    path('<slug:idem>/search/', include('search.urls', namespace="search")),
    path('<slug:slug>/settings/', IdemSettingsView.as_view(), name='settings'),
    path('<slug:slug>/icons/', IdemIconsView.as_view(), name='icons'),
    path('<slug:slug>/delete/', IdemDeleteView.as_view(), name='delete'),
]

main/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import (DashboardView, HomeView)


app_name = 'main'

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('about/', TemplateView.as_view(template_name='main/brochure/about.html'), name='about'),
    path('support/', TemplateView.as_view(template_name='main/brochure/support.html'), name='support'),
    path('privacy-policy/', TemplateView.as_view(template_name='main/brochure/privacy_policy.html'),
         name='privacy_policy'),
    path('terms-of-use/', TemplateView.as_view(template_name='main/brochure/terms_of_use.html'), name='terms_of_use'),
    path('', HomeView.as_view(), name='home')
]

post/urls.py
from django.urls import path

from .views import (PermanentPostView, PostCreateView, PostTagView, PostLikeView)


app_name = 'post'

urlpatterns = [
    path('<str:hash>/', PermanentPostView.as_view(), name='permanent'),
    path('<str:hash>/like/', PostLikeView.as_view(), name='like'),
    path('tags/', PostTagView.as_view(), name='tags'),
    path('', PostCreateView.as_view(), name='create')
]

search/urls.py
from django.urls import path

from .views import (SearchResultsView)


app_name = 'search'

urlpatterns = [
    path('', SearchResultsView.as_view(), name='results')
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.views.generic import (TemplateView, ListView)

from post.models import Post


class DashboardView(ListView):
    model = Post
    template_name = 'main/dashboard.html'

    def get_queryset(self):
        if self.request.user.idem:
            return Post.objects.dashboard(self.request.user.idem)
        else:
            return Post.objects.none()

    def get_template_names(self):
        if not self.request.user.idem:
            return ['main/brochure/dashboard.html']

        return super().get_template_names()


class HomeView(TemplateView):
    template_name = 'main/brochure/home.html'

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

main/templates/main/_footer.html
<footer class="footer bg-dark">
    <div class="container">
        <a href="{% url 'main:privacy_policy' %}">Privacy policy</a>
        <a class="ml-4" href="{% url 'main:terms_of_use' %}">Terms of use</a>
        <a class="ml-4" href="{% url 'account:cookies' %}">Cookies</a>
    </div>
</footer>

main/templates/main/_navigation.html
{% with request.resolver_match.namespace as namespace %}
{% with request.resolver_match.url_name as name %}
<ul class="navbar-nav mr-2">
    {% if user.is_authenticated %}
        <li class="nav-item">
            <div class="btn-group my-1">
                {% if user.idem %}
                    <a class="btn btn-secondary d-flex align-items-center" href="{% url 'main:dashboard' %}"><i class="fa fa-home"></i></a>
                    <a class="btn btn-{% if user.count_new_messages and namespace != 'message' %}info{% else %}secondary{% endif %} d-flex align-items-center" href="{% url 'message:list' %}">
                        {% if user.count_new_messages and namespace != 'message' %}
                            <i class="fa fa-envelope"></i>
                        {% else %}
                            <i class="fa fa-envelope-o"></i>
                        {% endif %}
                    </a>
                    <a href="{% url 'idem:idem' user.idem.slug %}" class="btn btn-secondary">{{ user.idem }}</a>
                {% else %}
                    <a class="btn btn-secondary d-flex align-items-center" href="{% url 'idem:create' %}"><i class="fa fa-star"></i></a>
                    <a href="{% url 'account:profile' %}" class="btn btn-secondary">{{ user }}</a>
                {% endif %}
                <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                    {% for idem in user.idems.all %}
                        <div class="dropdown-item d-flex align-items-center">
                            <a href="{% url 'idem:idem' idem.slug %}" class="flex-grow-1 w-100 mr-5">{{ idem }}</a>
                            {% if idem.id != user.idem.id %}
                            <a href="{% url 'idem:switch' idem.slug %}" class="ml-3 flex-shrink-1 btn btn-info" title="Default to {{ idem }}"><i class="fa fa-refresh"></i></a>
                            {% endif %}
                            <a href="{% url 'idem:post:create' idem.slug %}" class="ml-3 flex-shrink-1 btn btn-success" title="New post"><i class="fa fa-pencil"></i></a>
                            <a href="{% url 'idem:icons' idem.slug %}" class="ml-3 flex-shrink-1 btn btn-secondary" title="Icons"><i class="fa fa-picture-o"></i></a>
                            <a href="{% url 'idem:settings' idem.slug %}" class="ml-3 flex-shrink-1 btn btn-secondary" title="Settings"><i class="fa fa-cog"></i></a>
                        </div>
                        {% if forloop.last %}
                        <div class="dropdown-divider"></div>
                        {% endif %}
                    {% endfor %}
                    <a class="dropdown-item" href="{% url 'idem:create' %}"><i class="fa fa-star fa-fw"></i> Create new idem</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'account:profile' %}"><i class="fa fa-user fa-fw"></i> Account</a>
                    <a class="dropdown-item" href="{% url 'account:logout' %}"><i class="fa fa-sign-out fa-fw"></i> Log out</a>
                </div>
            </div>
        </li>
    {% else %}
        <li class="nav-item dropdown">
            <a class="nav-link" id="dropdownLoginMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" role="button" href="{% url 'account:login' %}">Log in</a>
            <form action="{% url 'account:login' %}" method="post" class="dropdown-menu p-4" aria-labelledby="dropdownLoginMenu">
                <div class="form-group">
                    <label for="id_username" class="sr-only">Username</label>
                    <input type="text" name="username" class="form-control" id="id_username" placeholder="Username">
                </div>
                <div class="form-group">
                    <label for="id_password" class="sr-only">Password</label>
                    <input type="password" name="password" class="form-control" id="id_password" placeholder="Password">
                </div>
                <div class="form-check">
                    <input type="checkbox" name="remember" class="form-check-input" id="id_remember">
                    <label class="form-check-label" for="id_remember">Remember me</label>
                </div>
                <button type="submit" class="btn btn-primary mt-3"><i class="fa fa-power-off"></i> Log in</button>
                {% csrf_token %}
            </form>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'account:register' %}">Get started</a>
        </li>
    {% endif %}
</ul>
{% endwith %}
{% endwith %}

main/templates/main/base.html
{% extends 'base.html' %}
{% load bootstrap4 static_version %}

{% block css %}
    <link rel="stylesheet" href="{% static_version 'main/css/site.css' %}">
{% endblock %}

{% block body %}
    {% block navigation %}
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'main:home' %}">Idem</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSiteContent" aria-controls="navbarSiteContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSiteContent">
            {% with request.resolver_match.namespace as namespace %}
            {% with request.resolver_match.url_name as name %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item{% if namespace == "main" and name == "about" %} active{% endif %}">
                    <a class="nav-link" href="{% url 'main:about' %}">About{% if namespace == "main" and name == "about" %}<span class="sr-only">(current)</span>{% endif %}</a>
                </li>
                <li class="nav-item{% if namespace == "main" and name == "support" %} active{% endif %}">
                    <a class="nav-link" href="{% url 'main:support' %}">Support{% if namespace == "main" and name == "support" %}<span class="sr-only">(current)</span>{% endif %}</a>
                </li>
            </ul>
            {% endwith %}
            {% endwith %}
            {% include 'main/_navigation.html' %}
            <form class="form-inline my-2 my-lg-0" method="POST" action="{% url 'search:results' %}">
                {% csrf_token %}
                <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    {% endblock %}
    {% block container %}
    <div class="container my-5" role="main">
        {% if user.is_validating and not messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <h4 class="alert-heading">Validate</h4>
                You shoooould have received one of those "yeah, it's me" e-mails at <strong>{{ user.email }}</strong> when you registered - give the link inside it a click and this will disappear.
                If you didn't, <a href="{% url 'account:resend_validate' %}" class="alert-link">click here to send the e-mail</a> again.
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
        {% endif %}
        {% bootstrap_messages %}
        {% block content %}
        <div class="row">
            <div class="col-md-9">{% block main %}{% endblock %}</div>
            <div class="col-md-3">{% block side %}{% endblock %}</div>
        </div>
        {% endblock %}
    </div>
    {% endblock %}
    {% block footer %}
    {% include 'main/_footer.html' %}
    {% endblock %}
{% endblock %}

main/templates/main/dashboard.html
{% extends 'main/base.html' %}
{% load post_tags %}

{% block main %}
    {% post_listings post_list show_all=False show_author=True %}
{% endblock %}