alteridem/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import (include, path)
from django.views.generic import RedirectView


urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url=settings.STATIC_URL + 'main/img/favicon.ico')),
    path('hijack/', include('hijack.urls', namespace='hijack')),
    # path('api/v1/', include('api.urls')),
    path('blog/', include('blog.urls', namespace="blog")),
    path('collection/', include('collection.urls', namespace="collection")),
    path('comment/', include('comment.urls', namespace="comment")),
    path('gallery/', include('gallery.urls', namespace="gallery")),
    path('post/', include('post.urls', namespace="post")),
    path('story/', include('story.urls', namespace="story")),
    path('video/', include('video.urls', namespace="video")),
    path('search/', include('search.urls', namespace="results")),
    path('inbox/', include('message.urls', namespace="message")),
    path('', include('account.urls', namespace="account")),
    path('', include('main.urls', namespace="main")),
    path('', include('idem.urls', namespace="idem")),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] \
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
        + urlpatterns

api/urls.py
from django.urls import (path, include)
from rest_framework import routers

from .views import (IdemViewSet, UserViewSet)


router = routers.DefaultRouter()
router.register(r'idems', IdemViewSet)
router.register(r'users', UserViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('auth/', include('rest_framework.urls', namespace='rest_framework'))
]

idem/urls.py
from django.urls import (include, path)

from message.views import MessageCreateView

from .views import (IdemCreateView, IdemView, IdemSwitchView, IdemFollowView, IdemUnfollowView, IdemSettingsView,
                    IdemDeleteView, IdemIconsView)


app_name = 'idem'

urlpatterns = [
    path('create/', IdemCreateView.as_view(), name='create'),
    path('<slug:slug>/', IdemView.as_view(), name='idem'),
    path('<slug:slug>/switch/', IdemSwitchView.as_view(), name='switch'),
    path('<slug:idem>/follow/', IdemFollowView.as_view(), name='follow'),
    path('<slug:idem>/unfollow/', IdemUnfollowView.as_view(), name='unfollow'),
    path('<slug:idem>/blog/', include('blog.urls', namespace="blog")),
    path('<slug:idem>/collection/', include('collection.urls', namespace="collection")),
    path('<slug:idem>/comment/', include('comment.urls', namespace="comment")),
    path('<slug:idem>/gallery/', include('gallery.urls', namespace="gallery")),
    path('<slug:idem>/inbox/', include('message.urls', namespace="inbox")),
    path('<slug:idem>/message/', include('message.urls', namespace="message")),
    path('<slug:idem>/post/', include('post.urls', namespace="post")),
    path('<slug:idem>/story/', include('story.urls', namespace="story")),
    path('<slug:idem>/video/', include('video.urls', namespace="video")),
    path('<slug:idem>/search/', include('search.urls', namespace="search")),
    path('<slug:slug>/settings/', IdemSettingsView.as_view(), name='settings'),
    path('<slug:slug>/icons/', IdemIconsView.as_view(), name='icons'),
    path('<slug:slug>/delete/', IdemDeleteView.as_view(), name='delete'),
]

main/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import (DashboardView, HomeView)


app_name = 'main'

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('about/', TemplateView.as_view(template_name='main/brochure/about.html'), name='about'),
    path('support/', TemplateView.as_view(template_name='main/brochure/support.html'), name='support'),
    path('privacy-policy/', TemplateView.as_view(template_name='main/brochure/privacy_policy.html'),
         name='privacy_policy'),
    path('terms-of-use/', TemplateView.as_view(template_name='main/brochure/terms_of_use.html'), name='terms_of_use'),
    path('', HomeView.as_view(), name='home')
]

post/urls.py
from django.urls import path

from .views import (PermanentPostView, PostCreateView, PostTagView, PostLikeView)


app_name = 'post'

urlpatterns = [
    path('<str:hash>/', PermanentPostView.as_view(), name='permanent'),
    path('<str:hash>/like/', PostLikeView.as_view(), name='like'),
    path('tags/', PostTagView.as_view(), name='tags'),
    path('', PostCreateView.as_view(), name='create')
]

idem/models/icon.py
from io import BytesIO
import random

from PIL import (ImageOps, Image)

from django.core.files.base import ContentFile
from django.db import models


class IconManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().select_related('idem').order_by('title')


def icon_file_name(instance, filename):
    random_str = ''.join((random.choice('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890'))
                         for x in range(10))

    return '/'.join(['idem', 'icons', '{}-{}-{}'.format(instance.idem.pk, random_str, filename.lower())])


class Icon(models.Model):
    idem = models.ForeignKey('idem.Idem', related_name='icons', on_delete=models.CASCADE)
    image = models.ImageField(upload_to=icon_file_name)
    title = models.CharField(max_length=255, blank=True)
    description = models.CharField(max_length=255, blank=True)
    note = models.CharField(max_length=255, blank=True)

    objects = IconManager()

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if self.pk is None:
            image = Image.open(self.image)

            method = Image.NEAREST if image.size == (100, 100) else Image.ANTIALIAS
            new_image = ImageOps.fit(image, (100, 100), method, centering=(0.5, 0.5))

            if image.format == 'GIF':
                new_format = 'GIF'

            elif image.format == 'PNG':
                new_format = 'PNG'

            else:
                new_format = 'JPEG'

            new_image_io = BytesIO()

            if image.format == 'GIF':
                new_image.save(new_image_io, save_all=True, format=new_format)
            else:
                new_image.save(new_image_io, format=new_format)

            tmp_name = self.image.name
            self.image.delete(save=False)

            self.image.save(tmp_name, content=ContentFile(new_image_io.getvalue()), save=False)

        super().save(force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)

    @property
    def original_file_name(self):
        try:
            return self.image.name.rsplit('.', 1)[0].split('-')[2]
        except (IndexError, AttributeError):
            return ''

    def __str__(self):
        return self.title or self.original_file_name

idem/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import (reverse, redirect)
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.functional import cached_property
from django.views.generic import (CreateView, FormView, UpdateView, DetailView, RedirectView)

from post.models import Post

from .decorators import idem_owner_required
from .forms import (IdemCreateForm, IdemDeleteForm, IdemSettingsForm, IconFormSet, IdemPasswordForm)
from .models import (Idem, Icon)
from .view_mixins import IdemMixin


class IdemCreateView(CreateView):
    model = Idem
    form_class = IdemCreateForm
    template_name = 'idem/create.html'

    def dispatch(self, request, *args, **kwargs):
        # ToDo - add message
        if request.user.is_anonymous:
            return redirect('{}?next={}'.format(reverse('account:login'), reverse('idem:create')))

        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('idem:idem', kwargs={'slug': self.object.slug})

    def form_valid(self, form):
        form.instance.user = self.request.user

        return super().form_valid(form)


@method_decorator(idem_owner_required, name='dispatch')
class IdemSettingsView(UpdateView):
    model = Idem
    form_class = IdemSettingsForm
    template_name = 'idem/settings.html'

    def form_valid(self, form):
        messages.success(self.request, 'Your idem settings have been updated')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('idem:settings', kwargs={'slug': self.object.slug})


@method_decorator(idem_owner_required, name='dispatch')
class IdemIconsView(FormView, DetailView):
    form_class = IconFormSet
    model = Idem
    template_name = 'idem/icons.html'

    @cached_property
    def idem(self):
        return self.get_object()

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)

        if not self.get_object().icons.exists():
            form.initial_extra = [{'is_default': True}]

        for f in form.forms:
            if f.instance and self.idem.icon and f.instance.pk == self.idem.icon.pk:
                f.fields['is_default'].widget.attrs = {'checked': True}

        return form

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'queryset': self.idem.icons.all()})
        return kwargs

    def get_success_url(self):
        return reverse('idem:icons', kwargs={'slug': self.kwargs.get('slug')})

    def form_invalid(self, form):
        self.object = self.idem

        return super().form_invalid(form)

    def form_valid(self, form):
        for icon in form:
            if icon.cleaned_data.get('DELETE') and icon.instance.pk:
                icon.instance.delete()
            elif icon.cleaned_data.get('image'):
                icon.instance.idem = self.idem

                icon.instance.save()

                if icon.cleaned_data.get('is_default', False):
                    self.idem.icon = icon.instance
                    self.idem.save()

        if self.idem.icons.exists() and not self.idem.icon:
            self.idem.icon = self.idem.icons.first()
            self.idem.icon.save()

        messages.success(self.request, 'Your icons have been updated')

        return super().form_valid(form)


@method_decorator(idem_owner_required, name='dispatch')
class IdemDeleteView(UpdateView):
    model = Idem
    template_name = 'idem/delete.html'
    form_class = IdemDeleteForm
    success_url = reverse_lazy('main:home')

    def form_valid(self, form):
        messages.success(self.request, 'Your idem has been deleted')

        return super().form_valid(form)


class IdemSwitchView(RedirectView):
    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)

        idem = self.request.user.idems.filter(slug=kwargs.get('slug')).get()

        if idem:
            response.set_cookie('idem', idem.id, max_age=31536000)

        return response

    def get_redirect_url(self, *args, **kwargs):
        if not self.request.user.is_authenticated or not self.request.META.get('HTTP_REFERER', None):
            return reverse('main:home')

        return self.request.META.get('HTTP_REFERER')


class IdemFollowView(IdemMixin, RedirectView):
    def get(self, request, *args, **kwargs):
        request.user.idem.follow(self.idem)

        return super().get(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return reverse('idem:idem', kwargs={'slug': self.idem.slug})


class IdemUnfollowView(IdemMixin, RedirectView):
    def get(self, request, *args, **kwargs):
        request.user.idem.unfollow(self.idem)

        return super().get(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return reverse('idem:idem', kwargs={'slug': self.idem.slug})


class IdemView(FormView, DetailView):
    model = Idem
    template_name = 'idem/idem.html'
    form_class = IdemPasswordForm

    def form_valid(self, form):
        idem = self.get_object()
        response = HttpResponseRedirect(self.request.path)

        if form.cleaned_data.get('password') == idem.password:
            # ToDo - make the cookie a bit more secure (time and hash or something?)
            response.set_cookie('idem_{}'.format(idem.pk), True)
        else:
            messages.error(self.request, 'That password is not the right password')

        return response

    def get_template_names(self):
        idem = self.get_object()

        if not idem.access == 1 \
                or 'idem_{}'.format(idem.pk) in self.request.COOKIES \
                or (self.request.user.is_authenticated and idem.user_id == self.request.user.id):
            return super().get_template_names()

        return ['idem/password.html']

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        if self.request.user.id == self.object.user_id:
            posts = Post.objects.owner(self.object, user=self.request.user)
        else:
            posts = Post.objects.visitor(self.object, user=self.request.user)

        data.update({
            'posts': posts
        })

        return data

idem/templates/idem/base.html
{% extends 'base.html' %}
{% load bootstrap4 static_version core_tags %}

{% block title %}{{ idem }}{% endblock %}

{% if not idem.access %}
    {% block meta_robots %}
        <meta name="robots" content="noindex,nofollow">
    {% endblock %}
{% endif %}

{% block css %}
    <link rel="stylesheet" href="{% static_version 'idem/css/idem.css' %}">
{% endblock %}

{% block body %}
    {% block navigation %}
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'idem:idem' idem.slug %}">
            {% icon idem %}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSiteContent" aria-controls="navbarSiteContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSiteContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:home' %}">Idem</a>
                </li>
            </ul>
            {% include 'main/_navigation.html' %}
            <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'idem:search:results' idem.slug %}">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    {% endblock %}
    {% block container %}
    <div class="container my-5">
        {% bootstrap_messages %}
        {% block content %}
            <div class="row">
                <div class="col-md-9">{% block main %}{% endblock %}</div>
                <div class="col-md-3">{% block side %}{% endblock %}</div>
            </div>
        {% endblock %}
    </div>
    {% endblock %}
    {% block footer %}
    {% include 'main/_footer.html' %}
    {% endblock %}
{% endblock %}

idem/templates/idem/delete.html
{% extends 'idem/idem.html' %}

{% block main %}
    <form method="post" action="{% url 'idem:delete' idem.slug %}">
        {% csrf_token %}
        <p>There's no cool-off period; there's no restore. If you hit delete, this idem and absolutely everything associated with it (except comments and ratings and whatnot) is gone poof <em>forever</em>.</p>
        <p>Cool?</p>
        <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Cool, I am really super sure I want this gone!</button>
    </form>
{% endblock %}

idem/templates/idem/idem.html
{% extends 'idem/base.html' %}
{% load post_tags core_tags idem_tags %}

{% block meta_robots %}
    {% if not idem.access %}
        <meta name='robots' content='noindex,nofollow,noarchive,nosnippet,noodp,noydir'>
    {% else %}
        <meta name="robots" content="index,follow,noodp,noydir">
    {% endif %}
{% endblock %}

{% block meta_description %}
    <meta name="description" content="{{ idem.about }}">
{% endblock %}

{% block main %}
    {% if posts %}
        {% post_listings posts show_all=True %}
    {% else %}
        {% if idem.user == user %}
            <p>You haven't posted anything yet, <a href="{% url 'idem:post:create' idem.slug %}">click here to go do that</a>.</p>
        {% else %}
            <p>There are no posts you can see here, sorry!</p>
        {% endif %}
    {% endif %}
{% endblock %}

{% block side %}
    <p class="text-center">{% icon idem %}</p>

     <h3><a href="{{ idem.full_url }}">{{ idem.title }}</a></h3>
    {% if idem.pronoun %}
        <p>{{ idem.pronoun }}</p>
    {% endif %}
    {% if idem.about %}
        <p>{{ idem.about|linebreaksbr }}</p>
    {% endif %}
    <p>
        <a href="{% url 'idem:message:create' idem.slug %}"><i class="fa fa-envelope-o"></i></a>
        {% if user.idem and user.idem.id != idem.id %}
            {% is_following user idem as following %}
            {% if following %}
                <a class="ml-3" href="{% url 'idem:unfollow' idem.slug %}">Unfollow</a>
            {% else %}
                <a class="ml-3" href="{% url 'idem:follow' idem.slug %}">Follow</a>
            {% endif %}
        {% endif %}
    </p>
    <ul class="list-group list-group-flush">
        {% if idem.count_collection %}
            {% list_breakdown idem=idem link='idem:collection:list' name='Collections' count=idem.count_collection icon="cubes" %}
        {% endif %}
        {% if idem.count_blog %}
            {% list_breakdown idem=idem link='idem:blog:list' name='Blog' count=idem.count_blog icon="align-justify" %}
        {% endif %}
        {% if idem.count_story %}
            {% list_breakdown idem=idem link='idem:story:list' name='Stories' count=idem.count_story icon="book" %}
        {% endif %}
        {% if idem.count_video %}
            {% list_breakdown idem=idem link='idem:video:list' name='Videos' count=idem.count_video icon="video-camera" %}
        {% endif %}
    </ul>
    {% if idem.count_following %}
        <h3>Following</h3>
        <div class="row">
            {% for following in idem.following.all %}
                <div class="col"><a href="{% url 'idem:idem' following.slug %}">{{ following }}</a></div>
            {% endfor %}
        </div>
    {% endif %}
    {% if idem.count_followers %}
        <h3>Followers</h3>
        <div class="row">
            {% for follower in idem.followers.all %}
                <div class="col"><a href="{% url 'idem:idem' follower.from_idem.slug %}">{{ follower.from_idem }}</a></div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

idem/templates/idem/settings.html
{% extends 'idem/base.html' %}
{% load bootstrap4 core_tags %}

{% block content %}
<h1><i class="fa fa-cog"></i> Settings</h1>
        {% bootstrap_form_errors form %}

<form method="post" action="{% url 'idem:settings' idem.slug %}" class="row mt-4">
    {% csrf_token %}
    <div class="col-3">
        <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <a class="nav-link active" id="v-pills-idem-tab" data-toggle="pill" href="#v-pills-idem" role="tab" aria-controls="v-pills-idem" aria-selected="true">Idem</a>
            <a class="nav-link" id="v-pills-access-tab" data-toggle="pill" href="#v-pills-access" role="tab" aria-controls="v-pills-access" aria-selected="false">Access</a>
            <a class="nav-link" id="v-pills-defaults-tab" data-toggle="pill" href="#v-pills-defaults" role="tab" aria-controls="v-pills-defaults" aria-selected="false">Defaults</a>
            <a class="nav-link" id="v-pills-sharing-tab" data-toggle="pill" href="#v-pills-sharing" role="tab" aria-controls="v-pills-sharing" aria-selected="false">Sharing</a>
            <a class="nav-link" id="v-pills-flagged-content-tab" data-toggle="pill" href="#v-pills-flagged-content" role="tab" aria-controls="v-pills-flagged-content" aria-selected="false">Flagged content</a>
            <a class="nav-link" id="v-pills-blocked-idems-tab" data-toggle="pill" href="#v-pills-blocked-idems" role="tab" aria-controls="v-pills-blocked-idems" aria-selected="false">Blocked idems</a>
            <a class="nav-link" id="v-pills-blocked-users-tab" data-toggle="pill" href="#v-pills-blocked-users" role="tab" aria-controls="v-pills-blocked-users" aria-selected="false">Blocked users</a>
        </div>
        <hr>
        <p class="text-center">
            <button class="btn btn-secondary" type="submit"><i class="fa fa-check"></i> Update</button>
            <a href="{% url 'idem:delete' idem.slug %}" class="btn btn-warning"><i class="fa fa-trash"></i> Delete</a>
        </p>
    </div>
    <div class="col-9">
        <div class="tab-content" id="v-pills-tabContent">
            <div class="tab-pane fade show active" id="v-pills-idem" role="tabpanel" aria-labelledby="v-pills-idem-tab">
                <fieldset>
                    <legend>Idem</legend>
                    {% bootstrap_field form.title layout="horizontal" %}
                    {% bootstrap_field form.slug layout="horizontal" %}
                    {% bootstrap_field form.pronoun layout="horizontal" %}
                    {% bootstrap_field form.about layout="inline" %}
                </fieldset>
            </div>
            <div class="tab-pane fade" id="v-pills-access" role="tabpanel" aria-labelledby="v-pills-access-tab">
                <fieldset>
                    <legend>Access</legend>
                    {% bootstrap_field form.access layout="inline" %}
                    {% password_show_hide form.password %}
                </fieldset>

                <hr>

                <h5>Private</h5>
                <p>No one but you can see your idem - no one but you can even hit the landing page! You won't show up in site searches, or on the Google.</p>

                <h5>Password protected</h5>
                <p>No one can see the posts in your idem, unless they have the password you've given them. <strong>This shouldn't be the password for your log in!</strong> Your posts still won't show on their dashboard, though, and you won't appear in site searches or on the Google.</p>

                <h5>Filtered</h5>
                <p>Only specific idems can see your idem exists, you'll show up in searches for those in the filter, but you won't appear on Google.</p>

                <h5>Followers</h5>
                <p>Only specific idems who are following you (and you haven't blocked) can see your idem exists, you'll show up in searches for those in the filter, but you won't appear on Google.</p>

                <h5>Public</h5>
                <p>Everyone can see you - this doesn't mean you can't change the access levels on individual posts, just that you're there for people to find. Site searches will find you, and Google may as well.</p>

                <hr>

                <h5 class="text-info">HOWEVER</h5>
                <p>This site is not at home to illegal shit, and there are bots botting their merry way around, and they don't care about your access settings. If one of those flags up an issue, it goes to a mod. Mods also don't care about your access settings.</p>
                <p>So, basically, be cool with the keeping to the Terms and Conditions and everything will be groovy.</p>

            </div>
            <div class="tab-pane fade" id="v-pills-defaults" role="tabpanel" aria-labelledby="v-pills-defaults-tab">
                <p>These are the default settings for your posts. All of them can be over-ridden on individual posts and updating here will not affect the settings on posts you've already made.</p>
                <fieldset>
                    <legend>Content</legend>
                    {% bootstrap_field form.default_rating layout="horizontal" %}
                    {% bootstrap_field form.default_warnings layout="horizontal" %}
                    {% bootstrap_field form.default_warnings_custom layout="horizontal" %}
                    {% bootstrap_field form.default_age layout="horizontal" %}
                </fieldset>
                <fieldset class="password-switch">
                    <legend>Access</legend>
                    {% bootstrap_field form.default_access layout="inline" %}
                    {% password_show_hide form.default_password %}
                </fieldset>
                <fieldset>
                    <legend>Comments</legend>
                    <div class="form-group">
                        <div class="form-check form-check-inline">
                          {{ form.default_allow_comments.0 }}
                        </div>
                        <div class="form-check form-check-inline">
                          {{ form.default_allow_comments.1 }}
                        </div>
                        <div class="form-check form-check-inline">
                          {{ form.default_allow_comments.2 }}
                        </div>
                        <small class="form-text text-muted">There's no moderation right now, so be... cautious.</small>
                    </div>
                </fieldset>
                <fieldset>
                    <legend>Interactivity</legend>
                    <div class="row">
                        <div class="col-4">{% bootstrap_field form.default_allow_annotate layout="inline" %}</div>
                        <div class="col-4">{% bootstrap_field form.default_allow_credit layout="inline" %}</div>
                        <div class="col-4">{% bootstrap_field form.default_allow_indexing layout="inline" %}</div>
                        <div class="col-4">{% bootstrap_field form.default_allow_likes layout="inline" %}</div>
                        <div class="col-4">{% bootstrap_field form.default_allow_search layout="inline" %}</div>
                        <div class="col-4">{% bootstrap_field form.default_allow_share layout="inline" %}</div>
                    </div>
                </fieldset>
                <fieldset>
                    <legend>Sharing</legend>
                    <div class="row">
                        <div class="col">{% bootstrap_field form.default_x_post_dw layout="inline" %}</div>
                        <div class="col">{% bootstrap_field form.default_x_post_lj layout="inline" %}</div>
                        <div class="col">{% bootstrap_field form.default_x_post_tumblr layout="inline" %}</div>
                    </div>
                    <small class="form-text text-muted">Cross-posting will only happen if you've given the account info in the Sharing settings.</small>
                </fieldset>
            </div>
            <div class="tab-pane fade" id="v-pills-sharing" role="tabpanel" aria-labelledby="v-pills-sharing-tab">
                <fieldset>
                    <legend>Sharing</legend>
                    <p>By using this functionality, you agree you are doing so at your own risk: Idem is not liable for any account details ending up in the hands of over-excited hackers.</p>
                    <h6>Dreamwidth</h6>
                    <div class="row">
                        <div class="col">{% bootstrap_field form.dw_username layout="inline" %}</div>
                        <div class="col">{% password_show_hide form.dw_password %}</div>
                    </div>
                    <h6>Livejournal</h6>
                    <div class="row">
                        <div class="col">{% bootstrap_field form.lj_username layout="inline" %}</div>
                        <div class="col">{% password_show_hide form.lj_password %}</div>
                    </div>
                </fieldset>
                <hr>
                <p>Click below if you have a strange and terrible urge to enable cross-posting to social media - this will take you off-site, so save any changes first!</p>
                <p class="text-center">
                    <a href="#" class="btn btn-primary"><i class="fa fa-tumblr fa-fw"></i></a>
                    <a href="#" class="btn btn-primary"><i class="fa fa-twitter fa-fw"></i></a>
                    <a href="#" class="btn btn-primary"><i class="fa fa-facebook fa-fw"></i></a>
                </p>
            </div>
            <div class="tab-pane fade" id="v-pills-flagged-content" role="tabpanel" aria-labelledby="v-pills-flagged-content-tab">
                <p class="alert alert-info">Flagged posts aren't hidden, but they display with an overview of which flags have been raised
                    so you can decided whether or not to click.</p>
                <div class="row">
                    <div class="col-md-8">
                        <p>These settings are applied automatically to warnings/ratings/age-rating/tags added by the original poster,
                            but can also be applied to those suggested by other users by adjusting your threshold %.</p>
                        <p class="text-muted">e.g., with a threshold of 20, if 20% of users who've seen a post have suggested it should have an 'adult' rating,
                            and you have 'adult' ratings flagged, the post will display for you as if the original poster given it an adult rating.</p>
                    </div>
                    <div class="col-md-4">
                        <h5>Threshold %</h5>
                        {% bootstrap_field form.user_flag_threshold %}
                        <small class="form-text text-muted">Leave blank to ignore user-recommended meta info.</small>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-4">
                        <h5>Maximum age</h5>
                        {% bootstrap_field form.flag_age %}
                        <h5>Ratings</h5>
                        {% bootstrap_field form.flag_ratings %}
                        <h5>Warnings</h5>
                        {% bootstrap_field form.flag_warnings %}
                    </div>
                    <div class="col-md-8">
                        <h5>Tags</h5>
                        <p>These have to be specific - there's no fuzzy matching at the moment. It's on the list.</p>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="v-pills-blocked-idems" role="tabpanel" aria-labelledby="v-pills-blocked-idems-tab">
                <fieldset>
                    <legend>Blocked idems</legend>
                    <p>Posts from any of these won't be removed, but they will have the contents hidden and a warning in
                    their place of who it's by and what's inside, so you can decided whether or not to click them.</p>
                </fieldset>
            </div>
            <div class="tab-pane fade" id="v-pills-blocked-users" role="tabpanel" aria-labelledby="v-pills-blocked-users-tab">
                <fieldset>
                    <legend>Blocked users</legend>
                    <p>There's a limited amount that can be done to completely block a user, and a whole lot of ways to get around those blocks.
                        If in doubt, your best bet is to limit people who can view and comment on your idem(s) to those you choose.</p>
                    <p>That said, you can give it a shot below.</p>
                    <p>The users you've blocked don't have a special message telling them that, they just get the default
                    "Yeah, no, this isn't a thing you can see."</p>
                </fieldset>
            </div>
        </div>
    </div>
</form>
{% endblock %}